trigger:
- testbranch

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DisplayHelloWorld
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - bash: echo hello

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  

- job: DisplayHiWorld
  dependsOn: DisplayHelloWorld
  steps:
  -  script: echo hi world

- job: DisplayMultiline
  dependsOn: DisplayHiWorld
  steps:
    - script: |
         echo Sudoko
         echo LudoKing
         echo Whatsapp

