trigger:
- testbranch

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: job1 
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - bash: echo hello

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: job2
  steps:
  -  script: echo helloworld

- job: job3
  steps:
    - script: |
         echo h
         echo e
         echo l
         echo lo
