trigger:
- testbranch

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:
    - script: echo stage build first job
  
  - job: SecondJob
    steps:
    - script: echo stage build second job

- stage: QA
  jobs:
  - job: FirstJob
    steps:
    - script: echo stage QA first job
  - job: SecondJob
    steps: 
    - script: echo stage QA secondjob
  
  
