trigger:
- testbranch

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  variables:
    environment: Dev
  jobs: 
  - job: FirstJob
    steps:
    - bash: echo stage build first job
    - bash: echo $(Build.BuildNumber)
    - bash: echo 
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: ls $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.tf'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - bash: ls $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'transformations'
        publishLocation: 'Container'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'test'
        publishLocation: 'pipeline'
        
#   - job: SecondJob
#     dependsOn: FirstJob
#     steps:
#     - script: |
#         echo value of testVar is $(testVar)
#         echo $(environment)
#         echo stage build second job

# - stage: QA
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     - script: |
#         echo stage QA first job
#         echo $(environment)
#   - job: SecondJob
#     dependsOn: FirstJob
#     steps: 
#     - script: echo stage QA secondjob
  
  
